name: buksam_flutter_practicum
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  appinio_swiper: ^2.1.1
  bloc: ^8.1.4
  cloud_firestore: ^5.1.0
  equatable: ^2.0.5
  file_picker: ^8.0.6
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flashy_tab_bar2: ^0.0.10
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.3
  get_it: ^7.7.0
  glass_kit: ^4.0.1
  google_generative_ai: ^0.4.3
  intl: ^0.19.0
  lottie: ^3.1.2
  pdf_image_renderer: ^0.7.0
  shimmer: ^3.0.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - .env
