// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhvccyX6kG1BJnbKHexU9aZLHx347ymhg',
    appId: '1:1006061029983:web:0dfe0cbf869ae5ab9f69ea',
    messagingSenderId: '1006061029983',
    projectId: 'practicum-booksam-ai-9909',
    authDomain: 'practicum-booksam-ai-9909.firebaseapp.com',
    storageBucket: 'practicum-booksam-ai-9909.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARrUiN1rrnct-uD3D_HfwsCclpivn85xY',
    appId: '1:1006061029983:android:4559403842f371fe9f69ea',
    messagingSenderId: '1006061029983',
    projectId: 'practicum-booksam-ai-9909',
    storageBucket: 'practicum-booksam-ai-9909.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlsELInGd-JN5DDIQLBdawQJfqHqB39So',
    appId: '1:1006061029983:ios:5e78ef449e6f847e9f69ea',
    messagingSenderId: '1006061029983',
    projectId: 'practicum-booksam-ai-9909',
    storageBucket: 'practicum-booksam-ai-9909.appspot.com',
    iosBundleId: 'com.example.buksamFlutterPracticum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlsELInGd-JN5DDIQLBdawQJfqHqB39So',
    appId: '1:1006061029983:ios:5e78ef449e6f847e9f69ea',
    messagingSenderId: '1006061029983',
    projectId: 'practicum-booksam-ai-9909',
    storageBucket: 'practicum-booksam-ai-9909.appspot.com',
    iosBundleId: 'com.example.buksamFlutterPracticum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhvccyX6kG1BJnbKHexU9aZLHx347ymhg',
    appId: '1:1006061029983:web:29f4784389dfe9929f69ea',
    messagingSenderId: '1006061029983',
    projectId: 'practicum-booksam-ai-9909',
    authDomain: 'practicum-booksam-ai-9909.firebaseapp.com',
    storageBucket: 'practicum-booksam-ai-9909.appspot.com',
  );
}
